modules:
  login:
    username:
    password:
    debug: true
  sign:
    debug: true

browser:
  driver: chromium
  type: chrome
  args:
    - "--mute-audio"
  headless: true
  skip_installation: false
  debug: true
