modules:
  login:
    username:
    password:
    debug: false
  sign:
    debug: false

browser:
  driver: chromium
  args:
    - "--mute-audio"
  headless: true
  skip_installation: true
  debug: true
