modules:
  login:
    username:
    password:
    debug: false
  sign:
    debug: false
  line_notify:
    personal_token: fake-token

browser:
  driver: chromium
  args:
    - "--mute-audio"
  headless: true
  skip_installation: true
  debug: true
