# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WORKDIR: ${{ github.workspace }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Create config yaml
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        cp ${{ env.WORKDIR }}/config/example.yaml ${{ env.WORKDIR }}/config/config.yaml
        sed -i -e 's/username:/username: ${{env.USERNAME}}/g' -e 's/password:/password ${{env.PASSWORD}}/g' ${{ env.WORKDIR }}/config/example.yaml

    - name: Build
      run: go build -o ${{ env.WORKDIR }}/build/main

    - name: Test
      run: go test
