# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Create config yaml
      run: |
        cp ${{ GITHUB_WORKSPACE }}/config/example.yaml ${{ GITHUB_WORKSPACE }}/config/config.yaml
        sed -i -e 's/username:/username: ${{USERNAME}}/g' -e 's/password:/password ${{USER_PASSWORD}}/g' ${{ GITHUB_WORKSPACE }}/config/example.yaml

    - name: Build
      run: go build -o ./build/main

    - name: Test
      run: go test
